// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otxohyfdnxapigqozofc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90eG9oeWZkbnhhcGlncW96b2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDc2OTYsImV4cCI6MjA2Njc4MzY5Nn0.VNfuNVpnSkiRSYUkmuXejDY35hGDN15Gl8On-VeBrYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);